
package comm.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CommunicationChannelService", targetNamespace = "http://soap.comm/", wsdlLocation = "http://localhost:8080/peer?wsdl")
public class CommunicationChannelService
    extends Service
{

    private final static URL COMMUNICATIONCHANNELSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/peer?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        COMMUNICATIONCHANNELSERVICE_WSDL_LOCATION = url;
    }

    public CommunicationChannelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommunicationChannelService(URL wsdlLocation) {
    	super(wsdlLocation, new QName("http://soap.comm/", "CommunicationChannelService"));
    }
    
    public CommunicationChannelService() {
        super(COMMUNICATIONCHANNELSERVICE_WSDL_LOCATION, new QName("http://soap.comm/", "CommunicationChannelService"));
    }

    /**
     * 
     * @return
     *     returns CommunicationChannel
     */
    @WebEndpoint(name = "CommunicationChannelPort")
    public CommunicationChannel getCommunicationChannelPort() {
        return (CommunicationChannel)super.getPort(new QName("http://soap.comm/", "CommunicationChannelPort"), CommunicationChannel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommunicationChannel
     */
    @WebEndpoint(name = "CommunicationChannelPort")
    public CommunicationChannel getCommunicationChannelPort(WebServiceFeature... features) {
        return (CommunicationChannel)super.getPort(new QName("http://soap.comm/", "CommunicationChannelPort"), CommunicationChannel.class, features);
    }

}
